name: Assets

on:
  push:
    tags:
      - "v*"

jobs:
  assets:
    name: Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - run: |
          version=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          # 1. pull tar files by tag (ref name)
          curl -fLsS https://get.docker.com/ | sh
          # pull amd
          docker pull --platform=linux/amd64 zengmingjian/web-ide:$version
          docker save zengmingjian/web-ide:$version | gzip > web-ide-$version-linux-amd64.tgz
          docker image rm zengmingjian/web-ide:$version
          # pull arm
          docker pull --platform=linux/arm64 zengmingjian/web-ide:$version
          docker save zengmingjian/web-ide:$version | gzip > web-ide-$version-linux-arm64.tgz
          docker image rm zengmingjian/web-ide:$version
          ls -al
          # 2. upload tar files
          release_id=$(
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/zanminkian/web-ide/releases/tags/${{ github.ref_name }}" | jq -r ".id"
          )
          echo "release id is $release_id"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/zanminkian/web-ide/releases/$release_id/assets?name=web-ide-$version-linux-amd64.tgz" \
            -T "web-ide-$version-linux-amd64.tgz" >/dev/null 2>&1
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/zanminkian/web-ide/releases/$release_id/assets?name=web-ide-$version-linux-arm64.tgz" \
            -T "web-ide-$version-linux-arm64.tgz" >/dev/null 2>&1
